#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint-staged && npm run eslint . --fix && npm run prettier --write .
npm run lint-staged && npm run eslint . --fix && npm run prettier --write .
npm run lint-staged && npm run lint && npm run prettier --write .
